Обчислити значення матричного виразу:
   - з використанням універсальних функцій бібліотеки NumPy;
   - за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо);
   - для обох випадків підрахувати час виконання скрипту та зробити висновок.

Порівняти всі рішення за допомогою функції ```numpy.allclose()```.

\begin{split}
        &(A-B)A + 3B,\\\\
        де\; &A = \begin{pmatrix} 3 & 2 & -5 \\ 4 & 2 & 0 \\ 1 & 1 & 2 \end{pmatrix},\; B = \begin{pmatrix} -1 & 2 & 4 \\ 0 & 3 & 2 \\ -1 & -3 & 4 \end{pmatrix}
\end{split}

In [1]:
import numpy as np
import time
import operator

A = [[3, 2, -5], [4, 2, 0], [1, 1, 2]]
B = [[-1, 2, 4], [0, 3, 2], [-1, -3, 4]]

In [2]:
start_time = time.perf_counter()

np_A = np.asarray(A)
np_B = np.asarray(B)
numpy_res = np.matmul(np_A - np_B, np_A) + np_B * 3

numpy_time = time.perf_counter() - start_time
print(numpy_res)

[[  0   5 -26]
 [  6  13 -18]
 [ 17   1  -2]]


In [3]:
start_time = time.perf_counter()

def matmul(a: list[list[float]], b) -> list[list[float]]:
    if isinstance(b, list):
        return [[sum(a_i * b_i for a_i, b_i in zip(a_row, b_col)) for b_col in zip(*b)] for a_row in a]
    if isinstance(b, (int, float)):
        return [[i * b for i in r] for r in a]
    raise ValueError()

def matsum(a: list[list[float]], b: list[list[float]]) -> list[list[float]]:
    return [list(map(operator.add, r_a, r_b)) for r_a, r_b in zip(a, b)]

def matsub(a: list[list[float]], b: list[list[float]]) -> list[list[float]]:
    return [list(map(operator.sub, r_a, r_b)) for r_a, r_b in zip(a, b)]

custom_res = matsum(matmul(matsub(A, B), A), matmul(B, 3))
    
custom_time = time.perf_counter() - start_time
custom_res = np.array(custom_res)
print(custom_res)

[[  0   5 -26]
 [  6  13 -18]
 [ 17   1  -2]]


In [4]:
print(f"The results are equal: {np.allclose(numpy_res, custom_res)}")
print(f"Time with NumPy: {round(numpy_time * 1000, 3)} ms.")
print(f"Time without NumPy: {round(custom_time * 1000, 3)} ms.")
print(f"NumPy is {round(custom_time/numpy_time, 3)} times faster.")

The results are equal: True
Time with NumPy: 0.114 ms.
Time without NumPy: 0.235 ms.
NumPy is 2.06 times faster.
