Розв’язати систему алгебраїчних рівнянь за допомогою формул Крамера і виконати перевірку за допомогою:
   - матричного множення;
   - оберненої матриці;
   - функції ```numpy.linalg.solve()```.

Порівняти всі рішення за допомогою функції ```numpy.allclose()```.

\begin{equation}
    \begin{cases}
      2x_1 - x_2 + 3x_3 + 2x_4 = 4\\
      3x_1 + 3x_2 + 3x_3 + 2x_4 = 6\\
      3x_1 - x_2 - x_3 + 2x_4 = 6\\
      3x_1 - x_2 + 3x_3 - x_4 = 6
    \end{cases}\,
\end{equation}

In [1]:
import numpy as np

A = [[2, -1, 3, 2], [3, 3, 3, 2], [3, -1, -1, 2], [3, -1, 3, -1]]
A = np.asarray(A)

b = [4, 6, 6, 6]
b = np.asarray(b)

print("A = ")
print(A)
print("\nb = ")
print(b)

A = 
[[ 2 -1  3  2]
 [ 3  3  3  2]
 [ 3 -1 -1  2]
 [ 3 -1  3 -1]]

b = 
[4 6 6 6]


##### Розв'язок за допомогою формул Крамера:

In [2]:
det = np.linalg.det(A)
n = len(A)

kramer_res = np.ndarray(n, dtype=np.float64)
for i in range(n):
    t = A.copy()
    t[:, i] = b
    kramer_res[i] = np.linalg.det(t) / det

print(kramer_res)

[2. 0. 0. 0.]


##### Перевірка матричним множенням:

In [3]:
matmul_test = np.matmul(A, kramer_res)

print(matmul_test)
print(f"Vectors are equal: {np.allclose(b, matmul_test)}")

[4. 6. 6. 6.]
Vectors are equal: True


##### Перевірка оберненою матрицею:

In [4]:
inv_matrix_res = np.matmul(np.linalg.inv(A), b)

print(inv_matrix_res)
print(f"Vectors are equal: {np.allclose(kramer_res, inv_matrix_res)}")

[2.00000000e+00 0.00000000e+00 0.00000000e+00 2.22044605e-16]
Vectors are equal: True


##### Перевірка функцією ```numpy.linalg.solve()```:

In [5]:
linalg_solve_res = np.linalg.solve(A, b)

print(linalg_solve_res)
print(f"Vectors are equal: {np.allclose(kramer_res, linalg_solve_res)}")

[ 2.00000000e+00 -4.54182146e-17  4.54182146e-17  6.05576195e-17]
Vectors are equal: True
