In [1]:
import numpy as np
import time
import random
import math

#### Вправа 1. 
##### Вводиться число n. Вивести масив розміру n×n, в якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0.

In [2]:
n = int(input("Enter n: "))

Enter n:  5


In [3]:
start_time = time.perf_counter()

numpy_res = np.diag(np.arange(1, n + 1))

numpy_time = time.perf_counter() - start_time
print(numpy_res)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [4]:
start_time = time.perf_counter()

custom_res = [[i + 1 if i == j else 0 for j in range(n)] for i in range(n)]
    
custom_time = time.perf_counter() - start_time
custom_res = np.array(custom_res)
print(custom_res)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [5]:
print(f"The results are equal: {np.array_equal(numpy_res, custom_res)}")
print(f"Time with NumPy: {round(numpy_time * 1000, 3)} ms.")
print(f"Time without NumPy: {round(custom_time * 1000, 3)} ms.")
print(f"NumPy is {round(custom_time/numpy_time, 3)} times faster.")

The results are equal: True
Time with NumPy: 0.08 ms.
Time without NumPy: 0.109 ms.
NumPy is 1.359 times faster.


#### Вправа 3. 
##### Вводяться 4 числа n, m, r, c. Вивести масив розміру n×m, в якому в кожному рядку з номером r і в кожному стовпчику з номером c стоять 0, а інші елементи дорівнюють 1.

In [6]:
n = int(input("Enter n: "))
m = int(input("Enter m: "))
r = int(input("Enter r: "))
c = int(input("Enter c: "))

Enter n:  6
Enter m:  7
Enter r:  2
Enter c:  3


In [7]:
start_time = time.perf_counter()

numpy_res = np.ones((n, m), dtype=int)
numpy_res[range(0, n, r), :] = 0
numpy_res[:, range(0, m, c)] = 0

numpy_time = time.perf_counter() - start_time
print(numpy_res)

[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]


In [8]:
start_time = time.perf_counter()

custom_res = [[0 if (i % r == 0 or j % c == 0) else 1 for j in range(m)] for i in range(n)]
    
custom_time = time.perf_counter() - start_time
custom_res = np.array(custom_res, dtype=int)
print(custom_res)

[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]


In [9]:
print(f"The results are equal: {np.array_equal(numpy_res, custom_res)}")
print(f"Time with NumPy: {round(numpy_time * 1000, 3)} ms.")
print(f"Time without NumPy: {round(custom_time * 1000, 3)} ms.")
print(f"NumPy is {round(custom_time/numpy_time, 3)} times faster.")

The results are equal: True
Time with NumPy: 0.19 ms.
Time without NumPy: 0.09 ms.
NumPy is 0.473 times faster.


#### Вправа 4. 
##### Вводяться числа n і m. Вивести масив розміру n×m, в якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0 до m–1, а всі інші елементи матриці дорівнюють 0.

In [10]:
n = int(input("Enter n: "))
m = int(input("Enter m: "))

Enter n:  4
Enter m:  3


In [11]:
start_time = time.perf_counter()

numpy_res = np.zeros((n, m), dtype=int)
numpy_res[0] = np.arange(0, m)

numpy_time = time.perf_counter() - start_time
print(numpy_res)

[[0 1 2]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [12]:
start_time = time.perf_counter()

custom_res = [[j if i == 0 else 0 for j in range(m)] for i in range(n)]
    
custom_time = time.perf_counter() - start_time
custom_res = np.array(custom_res, dtype=int)
print(custom_res)

[[0 1 2]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [13]:
print(f"The results are equal: {np.array_equal(numpy_res, custom_res)}")
print(f"Time with NumPy: {round(numpy_time * 1000, 3)} ms.")
print(f"Time without NumPy: {round(custom_time * 1000, 3)} ms.")
print(f"NumPy is {round(custom_time/numpy_time, 3)} times faster.")

The results are equal: True
Time with NumPy: 0.059 ms.
Time without NumPy: 0.07 ms.
NumPy is 1.186 times faster.


#### Вправа 5. 
##### Вводиться число n. Вивести масив розміру n×n, в якому в рядках з парними індексами стоять 1, а в інших – 0.

In [14]:
n = int(input("Enter n: "))

Enter n:  5


In [15]:
start_time = time.perf_counter()

numpy_res = np.zeros((n, n), dtype=int)
numpy_res[range(0, n, 2)] = 1

numpy_time = time.perf_counter() - start_time
print(numpy_res)

[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]


In [16]:
start_time = time.perf_counter()

custom_res = [[1 if i % 2 == 0 else 0 for j in range(n)] for i in range(n)]

custom_time = time.perf_counter() - start_time
custom_res = np.array(custom_res, dtype=int)
print(custom_res)

[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]


In [17]:
print(f"The results are equal: {np.array_equal(numpy_res, custom_res)}")
print(f"Time with NumPy: {round(numpy_time * 1000, 3)} ms.")
print(f"Time without NumPy: {round(custom_time * 1000, 3)} ms.")
print(f"NumPy is {round(custom_time/numpy_time, 3)} times faster.")

The results are equal: True
Time with NumPy: 0.111 ms.
Time without NumPy: 0.063 ms.
NumPy is 0.567 times faster.


#### Вправа 10.
##### Вводиться числа n i m. Створити масив випадкових значень n×m і обчислити мінімальне, максимальне значення, середнє та середньо квадратичне відхилення, округлене до 3 знаків після коми.

In [18]:
n = int(input("Enter n: "))
m = int(input("Enter m: "))

Enter n:  4
Enter m:  5


In [19]:
start_time = time.perf_counter()

numpy_res = np.random.rand(n, m)
min_value = np.min(numpy_res)
max_value = np.max(numpy_res)
mean_value = np.mean(numpy_res)
std_value = np.std(numpy_res)

numpy_time = time.perf_counter() - start_time
print(numpy_res)
print(f"Minimum: {round(min_value, 3)}")
print(f"Maximum: {round(max_value, 3)}")
print(f"Mean: {round(mean_value, 3)}")
print(f"Std: {round(std_value, 3)}")

[[0.62993841 0.89664814 0.2511168  0.21865621 0.2856455 ]
 [0.89982493 0.85039514 0.10811376 0.35524759 0.56914816]
 [0.8059246  0.42462552 0.43613815 0.54936616 0.84020319]
 [0.40216603 0.86730429 0.30306472 0.72473596 0.20191495]]
Minimum: 0.108
Maximum: 0.9
Mean: 0.531
Std: 0.26


In [20]:
start_time = time.perf_counter()

custom_res = [[random.random() for j in range(m)] for i in range(n)]
flat_custom_res = [e for r in custom_res for e in r]
min_value = min([min(r) for r in custom_res])
max_value = max([max(r) for r in custom_res])
mean_value = sum(flat_custom_res) / len(flat_custom_res)
std_value = math.sqrt(sum((e - mean_value) ** 2 for e in flat_custom_res) / len(flat_custom_res))

custom_time = time.perf_counter() - start_time
custom_res = np.array(custom_res, dtype=float)
print(custom_res)
print(f"Minimum: {round(min_value, 3)}")
print(f"Maximum: {round(max_value, 3)}")
print(f"Mean: {round(mean_value, 3)}")
print(f"Std: {round(std_value, 3)}")

[[0.2129653  0.3473839  0.55609854 0.02670884 0.51079228]
 [0.46365526 0.00829232 0.9259698  0.30192041 0.68076363]
 [0.16246928 0.23783258 0.65809759 0.22350691 0.93807536]
 [0.89311286 0.37456995 0.29153813 0.31408877 0.1281606 ]]
Minimum: 0.008
Maximum: 0.938
Mean: 0.413
Std: 0.277


In [21]:
print(f"Time with NumPy: {round(numpy_time * 1000, 3)} ms.")
print(f"Time without NumPy: {round(custom_time * 1000, 3)} ms.")
print(f"NumPy is {round(custom_time/numpy_time, 3)} times faster.")

Time with NumPy: 13.299 ms.
Time without NumPy: 0.164 ms.
NumPy is 0.012 times faster.


#### Вправа 12. 
##### Створити масив одиниць розміром n×n та створити в ньому «рамку», що утворюється з 0.

In [22]:
n = int(input("Enter n: "))

Enter n:  4


In [23]:
start_time = time.perf_counter()

numpy_res = np.ones((n, n), dtype=int)
numpy_res[(0, n - 1), ...] = 0
numpy_res[..., (0, n - 1)] = 0

numpy_time = time.perf_counter() - start_time
print(numpy_res)

[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


In [24]:
start_time = time.perf_counter()

custom_res = [[1 if (0 < i < n - 1 and 0 < j < n - 1) else 0 for j in range(n)] for i in range(n)]

custom_time = time.perf_counter() - start_time
custom_res = np.array(custom_res, dtype=int)
print(custom_res)

[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]


In [25]:
print(f"The results are equal: {np.array_equal(numpy_res, custom_res)}")
print(f"Time with NumPy: {round(numpy_time * 1000, 3)} ms.")
print(f"Time without NumPy: {round(custom_time * 1000, 3)} ms.")
print(f"NumPy is {round(custom_time/numpy_time, 3)} times faster.")

The results are equal: True
Time with NumPy: 0.115 ms.
Time without NumPy: 0.088 ms.
NumPy is 0.767 times faster.


#### Вправа 16. 
##### Заповнити вектор значеннями від 0 до n. Всі значення, що більші за n/4 та менші за 3n/4 замінити нулями.

In [26]:
n = int(input("Enter n: "))

Enter n:  10


In [27]:
start_time = time.perf_counter()

numpy_res = np.arange(n + 1, dtype=int)
numpy_res[np.logical_and(n / 4 < numpy_res, numpy_res < 3 * n / 4)] = 0

numpy_time = time.perf_counter() - start_time
print(numpy_res)

[ 0  1  2  0  0  0  0  0  8  9 10]


In [28]:
start_time = time.perf_counter()

custom_res = [i for i in range(n + 1)]
custom_res = [0 if (n / 4 < i < 3 * n / 4) else i for i in custom_res]

custom_time = time.perf_counter() - start_time
custom_res = np.array(custom_res, dtype=int)
print(custom_res)

[ 0  1  2  0  0  0  0  0  8  9 10]


In [29]:
print(f"The results are equal: {np.array_equal(numpy_res, custom_res)}")
print(f"Time with NumPy: {round(numpy_time * 1000, 3)} ms.")
print(f"Time without NumPy: {round(custom_time * 1000, 3)} ms.")
print(f"NumPy is {round(custom_time/numpy_time, 3)} times faster.")

The results are equal: True
Time with NumPy: 0.2 ms.
Time without NumPy: 0.067 ms.
NumPy is 0.335 times faster.


#### Вправа 17. 
##### Заповнити вектор значеннями від 0 до n. Замінити знаки для всіх значень, що менші за n/2 та більші за 3n/4 на протилежні.

In [30]:
n = int(input("Enter n: "))

Enter n:  10


In [31]:
start_time = time.perf_counter()

numpy_res = np.arange(n + 1, dtype=int)
numpy_res[np.logical_or(numpy_res < n / 2, numpy_res > 3 * n / 4)] *= -1

numpy_time = time.perf_counter() - start_time
print(numpy_res)

[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]


In [32]:
start_time = time.perf_counter()

custom_res = [i for i in range(n + 1)]
custom_res = [-i if (i < n / 2 or i > 3 * n / 4) else i for i in custom_res]

custom_time = time.perf_counter() - start_time
custom_res = np.array(custom_res, dtype=int)
print(custom_res)

[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]


In [33]:
print(f"The results are equal: {np.array_equal(numpy_res, custom_res)}")
print(f"Time with NumPy: {round(numpy_time * 1000, 3)} ms.")
print(f"Time without NumPy: {round(custom_time * 1000, 3)} ms.")
print(f"NumPy is {round(custom_time/numpy_time, 3)} times faster.")

The results are equal: True
Time with NumPy: 0.237 ms.
Time without NumPy: 0.069 ms.
NumPy is 0.294 times faster.


#### Вправа 21.
##### Ввести числа n і m. Згенерувати матрицю n×n випадкових цілих елементів з діапазону [0, m]. Замінити всі максимальні елементи цієї матриці на протилежні за знаком.

In [34]:
n = int(input("Enter n: "))
m = int(input("Enter m: "))

Enter n:  4
Enter m:  10


In [35]:
start_time = time.perf_counter()

numpy_res = np.random.randint(m + 1, size=(n, n), dtype=int)
numpy_res[numpy_res == np.max(numpy_res)] *= -1

numpy_time = time.perf_counter() - start_time
print(numpy_res)

[[  2   1   0   6]
 [  8   5 -10   0]
 [  1   5   7   3]
 [  0   8   4   8]]


In [36]:
start_time = time.perf_counter()

custom_res = [[random.randint(0, m) for j in range(n)] for i in range(n)]
max_value = max([max(r) for r in custom_res])
custom_res = [[-e if e == max_value else e for e in r] for r in custom_res]

custom_time = time.perf_counter() - start_time
custom_res = np.array(custom_res, dtype=int)
print(custom_res)

[[ 5  0  5  6]
 [ 0  4 -8  1]
 [-8  3 -8  4]
 [ 2  0  1  5]]


In [37]:
print(f"Time with NumPy: {round(numpy_time * 1000, 3)} ms.")
print(f"Time without NumPy: {round(custom_time * 1000, 3)} ms.")
print(f"NumPy is {round(custom_time/numpy_time, 3)} times faster.")

Time with NumPy: 13.84 ms.
Time without NumPy: 0.107 ms.
NumPy is 0.008 times faster.
